host: "192.168.1.10"
port: 8080
posthost: "192.168.1.11"
postport: 8080
timeout: 20
post_addr: api/shemt/processflow
state_topic: state
task_topic: task
det_topic: /myState
mqtt_addr: 6.tcp.vip.cpolar.cn
mqtt_port: 12594
mqtt_topic: test/topic
joint_topic: /joint_state
pose_topic: /amcl_pose